# Generated by Django 3.1.1 on 2020-09-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspots',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
