# Generated by Django 3.1.1 on 2020-09-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200918_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TouristSpots',
            new_name='TouristSpot',
        ),
    ]
