# Generated by Django 3.1.1 on 2020-09-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20200918_1907'),
        ('core', '0003_auto_20200918_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='attraction',
            field=models.ManyToManyField(to='attractions.Attraction'),
        ),
    ]
