# Generated by Django 3.1.1 on 2020-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentreviews', '0001_initial'),
        ('core', '0004_touristspot_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comment',
            field=models.ManyToManyField(to='commentreviews.Comment'),
        ),
    ]
