# Generated by Django 3.1.1 on 2020-09-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200920_2255'),
        ('core', '0005_touristspot_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='review',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
