# Generated by Django 3.1.1 on 2020-09-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
    ]
