# Generated by Django 3.1.1 on 2020-09-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20200918_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='attraction'),
        ),
    ]
